server:
  ssl:
    enabled: false

  servlet:
    session:
      timeout: 36000

spring:
  sleuth:
    sampler:
      probability: 1

  rabbitmq:
    host: 192.168.216.130
    port: 5672
    username: admin
    password: ZTM123ztm

  datasource:
    url: jdbc:mysql://192.168.216.130:3306/DS_erp?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZTM123ztm

  freemarker:
    check-template-location: false

  devtools:
    restart:
      log-condition-evaluation-delta: false
      enabled: false

  jpa:
    database: mysql

  application:
    name: DA-SHAN-FACTORY-ERP-SYSTEM

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.ds.factory.datasource.entities

#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin1:123456@localhost:7001/eureka/

---
spring:
  profiles: factory1
server:
  port: 8080

---
spring:
  profiles: factory2
server:
  port: 8008

---
spring:
  profiles: factory3
server:
  port: 9100
